import esbuild from "esbuild";
import esbuildSvelte from "esbuild-svelte";
import sveltePreprocess from "svelte-preprocess";
import process from "process";
import builtins from "builtin-modules";
import { writeFileSync } from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const external = [
  "obsidian",
  "electron",
  "@codemirror/autocomplete",
  "@codemirror/collab",
  "@codemirror/commands",
  "@codemirror/language",
  "@codemirror/lint",
  "@codemirror/search",
  "@codemirror/state",
  "@codemirror/view",
  "@lezer/common",
  "@lezer/highlight",
  "@lezer/lr",
  ...builtins,
];

// -- Pass 1: bundle the parse worker into a standalone string. --------------
// The design doc (section 6) requires DXF parsing off the main thread. Obsidian
// plugins ship a single main.js, so the worker is bundled separately and
// inlined as source, later instantiated from a Blob URL at runtime.
const workerResult = await esbuild.build({
  entryPoints: ["src/worker/parse.worker.ts"],
  bundle: true,
  format: "iife",
  platform: "browser",
  target: "es2018",
  minify: prod,
  write: false,
  logLevel: "info",
});
const workerCode = workerResult.outputFiles[0].text;
writeFileSync(
  "src/worker/inline.generated.ts",
  `// AUTO-GENERATED by esbuild.config.mjs — do not edit.\n` +
    `export const WORKER_SOURCE = ${JSON.stringify(workerCode)};\n`
);

// -- Pass 2: bundle the plugin (main thread + Svelte UI). -------------------
const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external,
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  plugins: [
    esbuildSvelte({
      compilerOptions: { css: "injected" },
      preprocess: sveltePreprocess(),
    }),
  ],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
